import type { Express } from "express";
import healthRouter from "./health.js";
import authRouter from "../modules/auth/auth.router.js";
import memberRouter from "../modules/members/member.router.js";
import planRouter from "../modules/plans/plan.router.js";
import subscriptionRouter from "../modules/subscriptions/subscription.router.js";
import classRouter from "../modules/classes/class.router.js";
import bookingRouter from "../modules/bookings/booking.router.js";
import attendanceRouter from "../modules/attendance/attendance.router.js";
import leadRouter from "../modules/leads/lead.router.js";
import billingRouter from "../modules/billing/billing.router.js";
import analyticsRouter from "../modules/analytics/analytics.router.js";
import accessRouter from "../modules/access/access.router.js";
import webhookRouter from "../modules/webhooks/webhook.router.js";
import messageRouter from "../modules/messages/message.router.js";

export const registerRoutes = (app: Express) => {
  app.use("/health", healthRouter);
  app.use("/api/auth", authRouter);
  app.use("/api/members", memberRouter);
  app.use("/api/plans", planRouter);
  app.use("/api/subscriptions", subscriptionRouter);
  app.use("/api/classes", classRouter);
  app.use("/api/bookings", bookingRouter);
  app.use("/api/attendance", attendanceRouter);
  app.use("/api/leads", leadRouter);
  app.use("/api/billing", billingRouter);
  app.use("/api/analytics", analyticsRouter);
  app.use("/api/access", accessRouter);
  app.use("/api/messages", messageRouter);
  app.use("/api/webhooks", webhookRouter);
};
